[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.5", features = ["derive"] }
starknet-crypto = "0.7.4"
ed25519-consensus = "2.1.0"
curve25519-dalek-ng = "4.1.1"
ed25519-dalek = "2.1"

sha2 = "0.9"
sha3 = "0.10"
aes-gcm = "0.10.3"
