[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
solana-client = "2.2.3"
solana-program = "2.2.1"
solana-sdk = "2.2.1"
darksol = { path = "../../DarkSol/programs/DarkSol" }
types = { path = "../types" }
rand = "0.9.0"
borsh = "1.5.6"
spl-associated-token-account = "6.0.0"


